apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-hello
  labels:
    #Project ID
    app: directed-cove-135122
spec:
  #Run two instances of our application
  replicas: 2
  template:
    metadata:
      labels:
        app: directed-cove-135122
    spec:
      #Container details
      containers:
        - name: cluster-rts
          image: us.gcr.io/directed-cove-135122/node:v3
          imagePullPolicy: Always
          #Ports to expose
          ports:
          - containerPort: 8080
