kind: Service
apiVersion: v1
metadata:
  #Service name
  name: php-hello
spec:
  selector:
    app: directed-cove-135122
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
